---
title: "Methodology"
format: gfm
params:
  sf_country:         "!!TEXT!!"
  sf_year:            "!!TEXT!!"
  sf_experience:      "!!TEXT!!"
  sf_perception:      "!!TEXT!!"
  sf_ssize:           "!!TEXT!!"
  sf_company:         "!!TEXT!!"
  sf_dates:           "!!TEXT!!"
  sf_nationality:     "!!TEXT!!"
  sf_location:        "!!TEXT!!"
  sf_projPop:         "!!TEXT!!"
  sf_surveyLang:      "!!TEXT!!"
  sf_comparison:      "!!TEXT!!"
  sf_sampling:        "!!TEXT!!"
  sf_ethnicity:       "!!TEXT!!"
  sf_qcontrol:        "!!TEXT!!"
  sf_education:       "!!TEXT!!"
  sf_region:          "!!TEXT!!"
  sf_historical:      "!!TEXT!!"
  sf_interviewing:    "!!TEXT!!"
  sd_coverage:        "!!TEXT!!"
  af_sunit_term:      "!!TEXT!!"
  af_sunit_number:    "!!TEXT!!"
  af_region_term:     "!!TEXT!!"
  af_region_number:   "!!TEXT!!"
  sd_rural_valueTXT:  "!!TEXT!!"
  sd_rural_value:     "!!TEXT!!"
  sd_urban_value:     "!!TEXT!!"
  sd_female_valueTXT: "!!TEXT!!"
  sd_female_value:    "!!TEXT!!"
  sd_male_value:      "!!TEXT!!"
  sd_highedu_value:   "!!TEXT!!"
  sd_lowedu_value:    "!!TEXT!!"
  tA_elegible:        "!!TEXT!!"
  tA_refusals:        "!!TEXT!!"
  tA_breaks:          "!!TEXT!!"
  tA_nocont:          "!!TEXT!!"
  tA_inelegible:      "!!TEXT!!"
  tA_noele:           "!!TEXT!!"
  tA_quotafil:        "!!TEXT!!"
---

                <!-- METHODOLOGY (page 36) -->
                <section id="Methodology">
                    <div class="container mb-4 pt-5">
                        <div class="row justify-content-center">
                            <div class="col-md-11 my-4">
                                <p class="title-p mb-0">METHODOLOGY </p>
                            </div>
                        </div>
                        <div class="row justify-content-center mb-3">
                            <div class="col-md-11">
                                <p class="mb-4">
                                    To present an image that accurately portrays the rule of law as experienced by ordinary people, data in this report is drawn from the General Population Poll (GPP), an original data source designed and collected by the World Justice Project (WJP). The GPP captures the experiences and perceptions of ordinary citizens concerning the performance of the state and its agents and the actual operation of the legal framework in their country.
                                    <br><br>
                                    The General Population Poll used to collect data in `r params$sf_country` in `r params$sf_year` features several new questions that highlight perceptions on issues salient to the region, including corruption, authoritarian behaviors, police performance, criminal justice, and security. In total, the General Population Poll questionnaire includes `r params$sf_perception` perception-based questions and `r params$sf_experience` experience-based questions, along with sociodemographic information on all respondents. Additionally, the GPP in `r params$sf_country` was administered to a sample of `r params$sf_ssize` respondents.
                                </p>
                                <p class="fs-20 mb-0"><b>Data Collection</b></p>
                                <p class="mb-4">
                                    The GPP in `r params$sf_country` was conducted for the <i>WJP's The Rule of Law in `r params$sf_country`: Key Findings from the General Population Poll 2022</i> with sampling, fieldwork, and data processing by `r params$sf_company`, based in `r params$sf_location`. `r params$sf_company` administered the surveys `r params$sf_dates`, conducting face-to-face interviews using a multi-stage stratified random sampling design. The target population group for this survey included `r (params$sf_nationality)`s aged 18 years or older residing across `r params$af_sunit_number` `r params$af_sunit_term` throughout the country.
                                </p>
                                <p class="mb-0 c-purple"><b>SAMPLE SIZE AND SAMPLE FRAME</b></p>
                                <p class="mb-4">
                                    The General Population Poll in `r params$sf_country` represents an achieved total sample size of `r params$sf_ssize` interviews distributed proportionally across `r params$af_region_number` `r params$af_region_term`. `r params$sf_projPop`
                                    <br><br>
                                    In order to address all relevant topics while controlling the questionnaire length, the World Justice Project split three of the survey modules into two versions (Option A and Option B) and randomly assigned one option to each respondent for each module. These modules included: Hypothetical Situations, Civic Participation, and Institutional Performance. Aside from these modules, the questionnaires are identical. A link to the complete survey instrument, in `r params$sf_surveyLang`, can be found in the Appendix of this report.
                                </p>
                                <p class="mb-0 c-purple"><b>SAMPLING</b></p>
                                <p class="mb-4">
                                    `r params$sf_sampling`
                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="page-number left-number"><b>36</b> III Project Design</div>
                </section>
                <!-- end METHODOLOGY -->

                <!-- DESCRIPTION OF THE SAMPLE (page 37) -->
                <section id="DescriptionSample">
                    <div class="container mb-4 pt-5">
                        <div class="row justify-content-center mb-3">
                            <div class="col-md-11">
                                <div class="row">
                                    <div class="col-md-4 mb-4">
                                        <div class="bg-light p-4">
                                            <div class="row">
                                                <div class="col bl-purple ml-3 mb-4">
                                                    <p class="fs-18 mb-0 ff-a c-purple">DESCRIPTION OF THE SAMPLE</p>
                                                </div>
                                                <div class="col-12">
                                                    <p class="mb-4">
                                                        <b class="c-purple">COVERAGE:</b> Interviews were distributed across regions to create a nationally representative sample. `r params$sd_coverage`
                                                    </p>
                                                    <p class="mb-4">
                                                        <b class="c-purple">GEOGRAPHY:</b> `r params$sd_rural_valueTXT` percent (`r params$sd_rural_value`) of respondents resided in rural areas and municipalities, while `r params$sd_urban_value` of respondents resided in metro areas or cities.
                                                    </p>
                                                    <p class="mb-4">
                                                        <b class="c-purple">RACIAL AND ETHNIC BACKGROUND:</b> `r params$sf_ethnicity`
                                                    </p>
                                                    <p class="mb-4">
                                                        <b class="c-purple">GENDER:</b> `r params$sd_female_valueTXT` percent (`r params$sd_female_value`) of respondents were female and `r params$sd_male_value` were male.
                                                    </p>
                                                    <p>
                                                        <b class="c-purple">EDUCATION:</b> `r params$sf_education`
                                                    </p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-8">
                                        <p class="c-purple"><b>RESPONSE RATES</b></p>
                                        <div class="table-responsive mb-2">
                                            <table class="table table-sm">
                                <tr class="bg-purple text-white">
                                    <td>Eligible household, non-interview</td>
                                    <td class="text-right">`r params$tA_elegible`</td>
                                </tr>
                                <tr>
                                    <td>Refusals</td>
                                    <td class="text-right">`r params$tA_refusals`</td>
                                </tr>
                                <tr>
                                    <td>Break-off</td>
                                    <td class="text-right">`r params$tA_breaks`</td>
                                </tr>
                                <tr>
                                    <td>Non-contact</td>
                                    <td class="text-right">`r params$tA_nocont`</td>
                                </tr>
                            </table>
                                        </div>
                                        <div class="table-responsive mb-4">
                                            <table class="table table-sm">
                                <tr class="bg-purple text-white">
                                    <td>Ineligible household</td>
                                    <td class="text-right">`r params$tA_inelegible`</td>
                                </tr>
                                <tr>
                                    <td>No eligible respondent in the household</td>
                                    <td class="text-right">`r params$tA_noele`</td>
                                </tr>
                                <tr>
                                    <td>Quota filled</td>
                                    <td class="text-right">`r params$tA_quotafil`</td>
                                </tr>
                            </table>
                                        </div>
                                        <p class="mb-0 c-purple"><b>INTERVIEWING AND QUALITY CONTROL</b></p>
                                        <p class="mb-4">
                                            `r params$sf_interviewing`
                                            <br><br>
                                            `r params$sf_qcontrol`
                                        </p>

                                        <p class="mb-0 c-purple"><b>DATA REVIEW AND JUSTIFICATION</b></p>
                                        <p class="mb-4">
                                            As part of the data analysis process, the team consulted several third-party sources in order to contextualize and validate perception-based data captured by the General Population Poll and compare it with the objective rule of law situation in-country. Peer data sources consulted include select indicators measured by the Latin American Public Opinion Project (LAPOP)'s <i>AmericasBarometer</i>, Latinobarómetro, Varieties of Democracy (V-Dem), Transparency International's <i>Corruption</i> <i>Perceptions</i> <i>Index</i>, the Bertelsmann Stiftung's <i>Transformation</i> <i>Index (BTI),</i> and Freedom House's <i>Freedom in</i> <i>the World</i>. While certain trends captured by the `r params$sf_year` General Population Poll in `r params$sf_country` are comparable to trends in perceptions data measured by other indices, the experiences, and perceptions presented in this report may not always coincide with the reality of `r params$sf_country`'s rule of law performance as measured by other sources.
                                        </p>

                                        <p class="mb-0 c-purple"><b>HISTORICAL DATA</b></p>
                                        <p class="mb-4">
                                            Historical data in this report derives from the <i>WJP Rule of Law Index®</i>'s General Population Poll that is typically administered every two to three years using a nationally representative probability sample ranging from 500 to 1,000 respondents. These household surveys were administered in the three largest cities of most countries until 2018, when the World Justice Project transitioned to nationally representative coverage as the preferred methodology for polling. The historical polling data used in this year's reports was collected in the following intervals: `r params$sf_historical`
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="page-number">III Project Design <b>37</b></div>
                </section>
                <!-- end DESCRIPTION OF THE SAMPLE -->

                <!-- ADDITIONAL COUNTRIES (page 38) -->
                <section id="AdditionalCountries">
                    <div class="container mb-4 pt-5">
                        <div class="row justify-content-center">
                            <div class="col-md-11 my-4">

                                <p class="mb-0 c-purple"><b>ADDITIONAL COUNTRIES</b></p>
                                <p class="mb-4">
                                    <i>The Rule of Law in `r params$sf_country`: Key Findings from the General Population Poll 2022</i> includes comparisons to the following `r params$sf_region` countries surveyed by the World Justice Project during the same period: `r params$sf_comparison`. This report is additionally part of a series that presents findings from the following five sub-regions within Latin America and the Caribbean: Andes (Bolivia, Colombia, Ecuador, Peru); Southern Cone (Argentina, Brazil, Paraguay); Eastern Caribbean (Barbados, Dominica, Grenada, St. Lucia, St. Vincent and the Grenadines, Trinidad and Tobago); Greater Antilles, The Bahamas, and the Guianas (The Bahamas, the Dominican Republic, Guyana, Haiti, Jamaica, Suriname); and Central America (Belize, Costa Rica, El Salvador, Guatemala, Honduras, Nicaragua, Panama). Together, these 26 countries are a portion of the 140 countries and jurisdictions included in the <i>WJP Rule of Law Index 2022</i> report. Detailed information regarding the methodology of the <i>Rule of Law Index</i> is available at: <a href="https://worldjusticeproject.org/" target="_blank" class="c-purple"><i>www.worldjusticeproject.org.</i></a>
                                </p>
                                <div class="table-responsive mb-4">
                                    <table class="table table-sm">
                                        <tr class="bg-purple text-white">
                                            <td>Country</td>
                                            <td>Polling Company</td>
                                            <td>Methodology</td>
                                            <td>Sample</td>
                                        </tr>
                                        <tr style = "background-color: #E8E4F9">
                                            <td>Argentina</td>
                                            <td>StatMark Group</td>
                                            <td>Face-to-face</td>
                                            <td>759</td>
                                        </tr>
                                        <tr>
                                            <td>The Bahamas</td>
                                            <td>DMR Insights Ltd.</td>
                                            <td>Face-to-face</td>
                                            <td>500</td>
                                        </tr>
                                        <tr style = "background-color: #E8E4F9">
                                            <td>Barbados</td>
                                            <td>DMR Insights Ltd.</td>
                                            <td>Face-to-face</td>
                                            <td>500</td>
                                        </tr>
                                        <tr>
                                            <td>Belize</td>
                                            <td>CID Gallup</td>
                                            <td>Face-to-face</td>
                                            <td>1,500</td>
                                        </tr>
                                        <tr style = "background-color: #E8E4F9">
                                            <td>Bolivia</td>
                                            <td>Captura Consulting</td>
                                            <td>Face-to-face</td>
                                            <td>1,000</td>
                                        </tr>
                                        <tr>
                                            <td>Brazil</td>
                                            <td>About Brazil Market Research</td>
                                            <td>Face-to-face</td>
                                            <td>1,109</td>
                                        </tr>
                                        <tr style = "background-color: #E8E4F9">
                                            <td>Colombia</td>
                                            <td>Tempo Group SA</td>
                                            <td>Face-to-face</td>
                                            <td>1,000</td>
                                        </tr>
                                        <tr>
                                            <td>Costa Rica</td>
                                            <td>CID Gallup</td>
                                            <td>Face-to-face</td>
                                            <td>1,005</td>
                                        </tr>
                                        <tr style = "background-color: #E8E4F9">
                                            <td>Dominica</td>
                                            <td>DMR Insights Ltd.</td>
                                            <td>Face-to-face</td>
                                            <td>500</td>
                                        </tr>
                                        <tr>
                                            <td>Dominican Republic</td>
                                            <td>CID Gallup</td>
                                            <td>Face-to-face</td>
                                            <td>1,002</td>
                                        </tr>
                                        <tr style = "background-color: #E8E4F9">
                                            <td>Ecuador</td>
                                            <td>StatMark Group</td>
                                            <td>Face-to-face</td>
                                            <td>1,005</td>
                                        </tr>
                                        <tr>
                                            <td>El Salvador</td>
                                            <td>CID Gallup</td>
                                            <td>Face-to-face</td>
                                            <td>2,010</td>
                                        </tr>
                                        <tr style = "background-color: #E8E4F9">
                                            <td>Grenada</td>
                                            <td>DMR Insights Ltd.</td>
                                            <td>Face-to-face</td>
                                            <td>500</td>
                                        </tr>
                                        <tr>
                                            <td>Guatemala</td>
                                            <td>Mercaplan</td>
                                            <td>Face-to-face</td>
                                            <td>2,002</td>
                                        </tr>
                                        <tr style = "background-color: #E8E4F9">
                                            <td>Guyana</td>
                                            <td>StatMark Group</td>
                                            <td>Face-to-face</td>
                                            <td>500</td>
                                        </tr>
                                        <tr>
                                            <td>Haiti</td>
                                            <td>CID Gallup</td>
                                            <td>Face-to-face</td>
                                            <td>507</td>
                                        </tr>
                                        <tr style = "background-color: #E8E4F9">
                                            <td>Honduras</td>
                                            <td>Mercaplan</td>
                                            <td>Face-to-face</td>
                                            <td>2,000</td>
                                        </tr>
                                        <tr>
                                            <td>Jamaica</td>
                                            <td>StatMark Group</td>
                                            <td>Face-to-face</td>
                                            <td>1,001</td>
                                        </tr>
                                        <tr style = "background-color: #E8E4F9">
                                            <td>Nicaragua</td>
                                            <td>CID Gallup</td>
                                            <td>Telephone</td>
                                            <td>1,014</td>
                                        </tr>
                                        <tr>
                                            <td>Panama</td>
                                            <td>CID Gallup</td>
                                            <td>Face-to-face</td>
                                            <td>2,023</td>
                                        </tr>
                                        <tr style = "background-color: #E8E4F9">
                                            <td>Paraguay</td>
                                            <td>Datum Internacional S.A./BM Business Partners</td>
                                            <td>Face-to-face</td>
                                            <td>1,000</td>
                                        </tr>
                                        <tr>
                                            <td>Peru</td>
                                            <td>Datum Internacional S.A.</td>
                                            <td>Face-to-face</td>
                                            <td>1,029</td>
                                        </tr>
                                        <tr style = "background-color: #E8E4F9">
                                            <td>St. Lucia</td>
                                            <td>DMR Insights Ltd.</td>
                                            <td>Face-to-face</td>
                                            <td>500</td>
                                        </tr>
                                        <tr>
                                            <td>St. Vincent and the Grenadines</td>
                                            <td>DMR Insights Ltd.</td>
                                            <td>Face-to-face</td>
                                            <td>500</td>
                                        </tr>
                                        <tr style = "background-color: #E8E4F9">
                                            <td>Suriname</td>
                                            <td>D3: Designs, Data, Decisions</td>
                                            <td>Face-to-face</td>
                                            <td>502</td>
                                        </tr>
                                        <tr>
                                            <td>Trinidad and Tobago</td>
                                            <td>CID Gallup</td>
                                            <td>Face-to-face</td>
                                            <td>1,001</td>
                                        </tr>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="page-number left-number"><b>38</b> III Project Design</div>
                </section>
                <!-- end ADDITIONAL COUNTRIES -->
